sudo: true
services:
  - docker

before_install:
  - docker pull quay.io/whisk/fastboot-postgres:9.6.5
  - docker pull cockroachdb/cockroach:v1.1.2

language: scala

scala:
  - 2.12.4

jdk:
  - oraclejdk8

script:
  - sbt test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete